apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: backstage-probe
  namespace: backstage
spec:
  interval: 60s
  module: https_2xx_insecure
  prober:
    url: sx-prometheus-blackbox-exporter.prometheus-blackbox-exporter.svc:9115
    path: /probe
  targets:
    staticConfig:
      labels:
        service: backstage
        healthcheck: kubrix
      static:
        - https://backstage.127-0-0-1.nip.io/.backstage/health/v1/liveness
