apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: keycloak-probe
  namespace: monitoring
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: sx-prometheus-blackbox-exporter.prometheus-blackbox-exporter.svc:9115
    path: /probe
  targets:
    staticConfig:
      labels:
        platform: kubrix
        service: keycloak
      static:
        - http://kubrix-keycloak-service.keycloak.svc:9000/health/ready
