apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: loki-probe
  namespace: loki
spec:
  interval: 60s
  module: https_2xx_insecure
  prober:
    url: sx-prometheus-blackbox-exporter.prometheus-blackbox-exporter.svc:9115
    path: /probe
  targets:
    staticConfig:
      labels:
        platform: kubrix
        service: loki
        component: read
      static:
        - http://loki-read.loki:3100/ready
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: loki-probe
  namespace: loki
spec:
  interval: 60s
  module: https_2xx_insecure
  prober:
    url: sx-prometheus-blackbox-exporter.prometheus-blackbox-exporter.svc:9115
    path: /probe
  targets:
    staticConfig:
      labels:
        platform: kubrix
        service: loki
        component: write
      static:
        - http://loki-write.loki:3100/ready
