apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: mimir-probe
spec:
  interval: 60s
  module: https_2xx_insecure
  prober:
    url: sx-prometheus-blackbox-exporter.prometheus-blackbox-exporter.svc:9115
    path: /probe
  targets:
    staticConfig:
      labels:
        platform: kubrix
        service: mimir
      static:
        - https://metrics-monitoring.127-0-0-1.nip.io/ready
