apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: mimir-probe
spec:
  interval: 60s
  module: https_2xx_insecure
  prober:
    url: sx-prometheus-blackbox-exporter.prometheus-blackbox-exporter.svc:9115
    path: /probe
  targets:
    staticConfig:
      labels:
        platform: kubrix
        service: mimir
        component: read
      static:
        - http://sx-mimir-query-frontend.mimir.svc:8080/ready
  ---
  apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: mimir-probe
spec:
  interval: 60s
  module: https_2xx_insecure
  prober:
    url: sx-prometheus-blackbox-exporter.prometheus-blackbox-exporter.svc:9115
    path: /probe
  targets:
    staticConfig:
      labels:
        platform: kubrix
        service: mimir
        component: write
      static:
        - http://sx-mimir-distributor.mimir.svc:8080/ready
